[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://scheduler-backend-three.vercel.app/api/:splat"
  status = 200
  force = true
  
