[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/api/user/login"
  to = "https://scheduler-backend-three.vercel.app/api/user/login"
  status = 200
  
